sudo: yes
dist: bionic
language: python

python:
- '3.7'

branches:
  only:
  - master

services:
  - postgresql

install:
- pip install tox-travis
before_script:
- psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
- createdb cicd -T template0

script:
- tox
